// Running ExtendScript in AE: build <WORK>/run/<name>.combined.jsx (lib + wrapper + user code), hand it to AE through
// osascript, wait for the log the script writes, print it, and wait for any PNGs it queued (saveFrameToPng is async).
import { closeSync, mkdirSync, openSync, readFileSync, readSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { aeApp, DEBUG, LIB, RUN_TIMEOUT, SNAP_TIMEOUT, WORK } from "./env.ts";
import { prep } from "./lint.ts";
import { err, exists, jsstr, need, run, sleep } from "./util.ts";

export function aeRunning(): boolean {
  const r = run("osascript", ["-e", `application "${aeApp()}" is running`]);
  return r.stdout.trim() === "true";
}

/** A complete PNG: non-empty and ends with the IEND chunk. */
export function pngDone(p: string): boolean {
  let fd = -1;
  try {
    const size = statSync(p).size;
    if (size < 8) return false;
    fd = openSync(p, "r");
    const b = Buffer.alloc(8);
    readSync(fd, b, 0, 8, size - 8);
    return b.toString("hex") === "49454e44ae426082";
  } catch {
    return false;
  } finally {
    if (fd >= 0) closeSync(fd);
  }
}

/** Wait until every PNG is complete. Returns 0, or 3 on timeout (after listing the missing files). */
export async function waitPngs(timeoutSec: number, paths: string[]): Promise<number> {
  if (!paths.length) return 0;
  const start = Date.now();
  let first = -1;
  for (;;) {
    const missing = paths.filter((p) => !pngDone(p));
    if (first < 0) first = missing.length;
    if (!missing.length) {
      if (DEBUG) err(`ae: PNGs: ${first} of ${paths.length} missing at first check, all ready after ${Math.floor((Date.now() - start) / 1000)}s`);
      return 0;
    }
    if (Date.now() - start >= timeoutSec * 1000) {
      err(`ae: timeout: ${missing.length} of ${paths.length} PNG(s) still missing after ${timeoutSec}s:`);
      for (const p of missing) err("  " + p);
      return 3;
    }
    await sleep(300);
  }
}

export interface RunOptions {
  undo: boolean;
  label: string;
  quiet?: boolean; // print the log only when it has an ERR line (to stderr)
  timeout?: number; // seconds to wait for the log
  snapTimeout?: number; // seconds to wait for queued PNGs
  internal?: boolean; // generated by the CLI itself: no lint warnings
  rollback?: boolean; // undo the step right away when the script fails
  exprCheck?: boolean; // afterwards, WARN about expression errors in the comps the script looked up (mutating runs)
  diff?: { before: string; after: string }; // write project snapshots before and after the script (ae run --diff)
}

/**
 * Run a user .jsx in AE. Returns the exit code: 0 ok, 1 an ERR line was logged, 2 lint/syntax error (not run),
 * 3 AE not running / osascript failed / timeout.
 */
export async function runJsx(user: string, log: string, o: RunOptions): Promise<number> {
  need("osascript");
  if (!exists(LIB)) {
    err(`ae: lib.jsx not found next to ae (${LIB})`);
    return 2;
  }
  mkdirSync(path.join(WORK, "run"), { recursive: true });
  const base = path.basename(user).replace(/\.jsx$/, "");
  const prepped = path.join(WORK, "run", base + ".prep.jsx");
  const combined = path.join(WORK, "run", base + ".combined.jsx");
  if (!prep(user, prepped, LIB, !o.internal)) {
    err(`ae: ${user} failed the syntax/lint check; not run`);
    return 2;
  }
  if (!aeRunning()) {
    err(`ae: '${aeApp()}' is not running`);
    return 3;
  }
  const lib = readFileSync(LIB, "utf8");
  const offset = (lib.match(/\n/g)?.length ?? 0) + 1; // combined-file line where the user's line 1 lands
  if (o.diff) for (const f of [o.diff.before, o.diff.after]) rmSync(f, { force: true });
  // everything before the user's code stays on one line: `offset` maps AE's line numbers back to the user's file
  const before = o.diff ? `AE._snapshotTo(${jsstr(o.diff.before)});` : "";
  const after = (o.exprCheck ? "AE._checkExprs();" : "") + (o.diff ? `AE._snapshotTo(${jsstr(o.diff.after)});` : "");
  writeFileSync(
    combined,
    "try{" +
      lib +
      `AE._begin(${jsstr(log)}, ${jsstr(user)}, ${offset}, ${jsstr(WORK)}, ${o.rollback === true});${before}AE.run(${jsstr(o.label)}, function (log) {\n` +
      readFileSync(prepped, "utf8") +
      `\n}, {undo: ${o.undo}, silent: true});\n${after}AE._end();\n` +
      `}catch(__e){var __f=new File(${jsstr(log)});__f.encoding="UTF-8";__f.lineFeed="Unix";__f.open("w");__f.write("ERR fatal (lib/wrapper): "+__e.message+" line "+__e.line+"\\n");__f.close();}\n`,
  );
  mkdirSync(path.dirname(log), { recursive: true });
  rmSync(log, { force: true });
  rmSync(log + ".part", { force: true });
  const r = run("osascript", ["-e", "on run argv", "-e", `tell application "${aeApp()}" to DoScriptFile (item 1 of argv)`, "-e", "end run", combined]);
  if (r.status !== 0) {
    err(`ae: osascript failed: ${(r.stdout + r.stderr).trim()}`);
    return 3;
  }
  const timeout = o.timeout ?? RUN_TIMEOUT;
  const start = Date.now();
  let warned = false;
  while (!exists(log)) {
    const waited = (Date.now() - start) / 1000;
    if (waited >= timeout) {
      err(`ae: no log after ${timeout}s (${log}). AE busy, or a modal dialog is open in AE? combined script: ${combined}`);
      return 3;
    }
    if (!warned && waited >= 10) {
      err("ae: waiting for AE...");
      warned = true;
    }
    await sleep(200);
  }
  const text = readFileSync(log, "utf8");
  const lines = text.split("\n");
  const failed = lines.some((l) => l.startsWith("ERR"));
  if (o.quiet) {
    if (failed) process.stderr.write(text);
  } else {
    process.stdout.write(text);
  }
  const pngs = lines.filter((l) => l.startsWith("PNG ")).map((l) => l.slice(4));
  if (pngs.length) {
    const code = await waitPngs(o.snapTimeout ?? SNAP_TIMEOUT, pngs);
    if (code) return code;
    if (!o.quiet) err(`ae: ${pngs.length} PNG(s) ready`);
  }
  return failed ? 1 : 0;
}

/** Write a generated script to <WORK>/<dir>/<name>.jsx and run it; the log goes next to it. */
export async function runSnippet(dir: string, name: string, code: string, o: RunOptions): Promise<{ code: number; log: string }> {
  const d = path.join(WORK, dir);
  mkdirSync(d, { recursive: true });
  const f = path.join(d, name + ".jsx");
  const log = path.join(d, name + ".log");
  writeFileSync(f, code);
  return { code: await runJsx(f, log, { internal: true, ...o }), log };
}

export function readLog(log: string): string {
  try {
    return readFileSync(log, "utf8");
  } catch {
    return "";
  }
}
